[package]
name = "zk1A2B"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bn254 = "0.5.0"
ark-circom = "0.5.0"
ark-groth16 = "0.5.0"
ark-serialize = "0.5.0"
ark-snark = "0.5.1"
hex = "0.4.3"
ark-std = "0.5.0"
tokio = { version = "1.0", features = ["full"] }
